name: purity_oauth2
version: 0.0.0
author: Daniel Robinson <daniel.robinson.dart@gmail.com>
description: An OAuth2 library for the Purity framework
homepage: http://github.com/0xor1/purity_oauth2
environment:
  sdk: '>=1.3.0+6 <2.0.0'
dependencies:
  purity: '>=0.7.1 <0.8.0'
  unittest: any
